language: android
sudo: false
jdk: oraclejdk8

# https://github.com/travis-ci/travis-cookbooks/blob/master/ci_environment/android-sdk/attributes/default.rb
# "tools" is needed see https://github.com/travis-ci/travis-ci/issues/5036
android:
  components:
    - tools
    - platform-tools
    - android-24
    - build-tools-24.0.1
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository


script: ./gradlew test